language: python
python:
- '3.6'
sudo: required
services:
- docker
before_install:
- docker --version
- docker-compose --version
- docker-compose -f docker/ci.docker-compose.yml pull
- docker-compose -f docker/ci.docker-compose.yml up -d
- sleep 180 
- docker exec docker_twitterrestharvester_1 python -m unittest discover
install: pip install -r requirements/common.txt -r requirements/master.txt
script: python -m unittest discover
notifications:
  email:
  - sfm@gwu.edu
  slack:
    secure: sHFsZPBO1rnJc75SnP2xIQAjbT6TIpc5W4tY5AI2O2tyzEorCG9BbVwiV0/uC++TMnqkbCsEqThlwUHGzm6RwnNjy5B5vcqgMU116WY/E9S0qvzjpQnaADXhLOFrwCVINFkCjHaepF3Q/Lr0KYWS7W83mJPJ3IfST7e4RsLuTweyeH0dnF/BwAxxqzhvx5M0S7B6MijrfAm98qnmUCLGylzwSV48VUHRmgcIbkwQwmAsw8bzEd+bTW6LPymktDsz4wwZR9C33yumQU4HTMhKKGt4G2PsPxwxx14WegO4y5htB0Z1A68nF/mQGFxDcDU49l0G9VMXJ3pBMILJJ7lLpqmLQK7QXqmArtIur4hIUsFg72VYeu0fWhDNSJCCOlvcXTDBE0XvfIBWsPnxcPtrX5GUahBrUQRVhojiua97ozM5yMTAWWLjLckAhmSQYrJNxxeN4CRUinsH5QNjdgXsU/APHr5Dhu1H4nl3BUPGmySb+MeDBj6Pfl9dxuEKo46n+HDuR+tKYL5zwMOqDIZ74XZWRi/ZZZidacAaNQD19TmInVTFiFA76jZqgJCQAeSo2q6RsYKRrJ2mehW4dr3kY8wAuaYe2oAY7T52hOJja6w/0OLfucQ7ro5vRU/mKmU6eaOrpP/CAcUkzag5RHCSvKNNLiCzYgN7yTd3PouxrfM=
    on_success: never
