FROM gwul/sfm-base@sha256:9ba2b7d757cf1a285e9af6fbcc35916155779f2944d3018247176a29e0904973
MAINTAINER Justin Littman <justinlittman@gwu.edu>

# Install supervisor
RUN apt-get update && apt-get install -y \
    supervisor=3.0r1-1
VOLUME /etc/supervisor/conf.d

ADD . /opt/sfm-twitter-harvester/
WORKDIR /opt/sfm-twitter-harvester
RUN pip install -r requirements/common.txt -r requirements/release.txt

CMD sh /opt/sfm-setup/setup_reqs.sh \
    && appdeps.py --wait-secs 60 --port-wait mq:5672 --file-wait /sfm-data/collection_set --file-wait /sfm-data/containers \
    && supervisord -c /etc/supervisor/supervisord.conf \
    && stream_consumer.py mq $RABBITMQ_USER $RABBITMQ_PASSWORD twitter_harvester harvest.start.twitter.twitter_filter,harvest.start.twitter.twitter_sample /opt/sfm-twitter-harvester/twitter_harvester.py /sfm-data/containers/$HOSTNAME --debug=$DEBUG --debug-warcprox=$DEBUG_WARCPROX --tries=$HARVEST_TRIES
