FROM gwul/sfm-base@sha256:07b3495d4496d603d464b3f829f92e61c6d27da8b773e1076e1b6ffcfd643eaf
MAINTAINER Justin Littman <justinlittman@gwu.edu>

ADD . /opt/sfm-twitter-harvester/
WORKDIR /opt/sfm-twitter-harvester
RUN pip install -r requirements/common.txt -r requirements/release.txt

CMD sh /opt/sfm-setup/setup_reqs.sh \
    && appdeps.py --wait-secs 60 --port-wait mq:5672 --file-wait /sfm-data/collection_set --file-wait /sfm-data/containers \
    && gosu sfm python twitter_harvester.py --debug=$DEBUG --debug-warcprox=$DEBUG_WARCPROX service mq $RABBITMQ_USER $RABBITMQ_PASSWORD /sfm-data/containers/$HOSTNAME --tries=$HARVEST_TRIES --priority-queues=$PRIORITY_QUEUES
