FROM gwul/sfm-base@sha256:bf84472ee4819b86a90a39c184f190b5ab769026eb427fe784625f3148490e55
MAINTAINER Justin Littman <justinlittman@gwu.edu>

# Install supervisor
RUN apt-get update && apt-get install -y \
    supervisor=3.0r1-1+deb8u1
VOLUME /etc/supervisor/conf.d

ADD . /opt/sfm-twitter-harvester/
WORKDIR /opt/sfm-twitter-harvester
RUN pip install -r requirements/common.txt -r requirements/release.txt

ADD docker/stream-harvester/invoke.sh /opt/sfm-setup/
RUN chmod +x /opt/sfm-setup/invoke.sh

ENTRYPOINT ["/opt/sfm-setup/invoke.sh"]
