version: "2"
services:
  rabbit:
      image: rabbitmq@sha256:d374d705b3f16e3f0ee34ea14d8599cb4c1f1604ae6deef5fefbaf063d0bb9c6
      environment:
          - TZ=America/New_York
          - SFM_RABBITMQ_DEFAULT_USER=sfm_user
          - SFM_RABBITMQ_DEFAULT_PASS=password
  data:
      image: gwul/sfm-data:master
      volumes:
           - /sfm-data
      environment:
          - TZ=America/New_York
          - SFM_UID=900
          - SFM_GID=900
  twitterrestharvester:
      image: gwul/sfm-twitter-rest-harvester:master
      links:
          - rabbit:mq
      volumes:
          - "..:/opt/sfm-twitter-harvester"
      volumes_from:
          - data
      environment:
          - TZ=America/New_York
          - TWITTER_CONSUMER_KEY
          - TWITTER_CONSUMER_SECRET
          - TWITTER_ACCESS_TOKEN
          - TWITTER_ACCESS_TOKEN_SECRET
          - DEBUG=true
          - SFM_RABBITMQ_USER=sfm_user
          - SFM_RABBITMQ_PASSWORD=password
          - SFM_RABBITMQ_HOST=mq
          - SFM_RABBITMQ_PORT=5672
          - SFM_REQS=master
          - HARVEST_TRIES=3
          - SFM_UID=900
          - SFM_GID=900
  twitterstreamharvester:
      image: gwul/sfm-twitter-stream-harvester:master
      links:
          - rabbit:mq
      volumes:
          - "..:/opt/sfm-twitter-harvester"
      volumes_from:
          - data
      environment:
          - TZ=America/New_York
          - TWITTER_CONSUMER_KEY
          - TWITTER_CONSUMER_SECRET
          - TWITTER_ACCESS_TOKEN
          - TWITTER_ACCESS_TOKEN_SECRET
          - DEBUG=true
          - SFM_RABBITMQ_USER=sfm_user
          - SFM_RABBITMQ_PASSWORD=password
          - SFM_RABBITMQ_HOST=mq
          - SFM_RABBITMQ_PORT=5672
          - SFM_REQS=master
          - HARVEST_TRIES=3
          - SFM_UID=900
          - SFM_GID=900
