#!/bin/bash
echo $DOCKERFILE_PATH 
echo $IMAGE_NAME
if [ $DOCKER_TAG == "master" ]
then
    docker build -f $DOCKERFILE_PATH --build-arg build_version=master -t $IMAGE_NAME . 
else
    docker build  -f $DOCKERFILE_PATH -t $IMAGE_NAME .
fi